version: "3.8"
services:
  yolo:
    build: .
    ports:
      - "8667:8667"
    volumes:
      - ./uploads:/app/uploads  # For uploaded images
      - yolo-data:/app/data     # For SQLite database
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    restart: unless-stopped

volumes:
  yolo-data: