version: "3.8"
services:
  yolo:
    build: .
    ports:
      - "8667:8667"
    volumes:
      - ./uploads:/app/uploads  # For uploaded images
      - yolo-data:/app/data     # For SQLite database
    restart: unless-stopped

volumes:
  yolo-data: