version: "3.8"
services:
  yolo:
    build: .
    ports:
      - "8667:8667"
    restart: always
    volumes:
      - ./uploads:/app/uploads
      # Remove or change this line:
      # - ./data:/app
      - .:/app  # Mount the entire current dir so app.py is visible
